/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.40.0.0
 *
 * Project: 'GPIO' 
 * Target:  'Target 1' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "gd32f30x.h"

/* ARM::RTOS&FreeRTOS:Config&FreeRTOS@11.1.0 */
#define RTE_RTOS_FreeRTOS_CONFIG        /* RTOS FreeRTOS Config for FreeRTOS API */
/* ARM::RTOS&FreeRTOS:Core&Cortex-M@11.1.0 */
#define RTE_RTOS_FreeRTOS_CORE          /* RTOS FreeRTOS Core */
/* ARM::RTOS&FreeRTOS:Coroutines@11.1.0 */
#define RTE_RTOS_FreeRTOS_COROUTINE     /* RTOS FreeRTOS Co-routines */
/* ARM::RTOS&FreeRTOS:Event Groups@11.1.0 */
#define RTE_RTOS_FreeRTOS_EVENTGROUPS   /* RTOS FreeRTOS Event Groups */
/* ARM::RTOS&FreeRTOS:Heap&Heap_1@11.1.0 */
#define RTE_RTOS_FreeRTOS_HEAP_1        /* RTOS FreeRTOS Heap 1 */
/* ARM::RTOS&FreeRTOS:Message Buffer@11.1.0 */
#define RTE_RTOS_FreeRTOS_MESSAGE_BUFFER /* RTOS FreeRTOS Message Buffers */
/* ARM::RTOS&FreeRTOS:Stream Buffer@11.1.0 */
#define RTE_RTOS_FreeRTOS_STREAM_BUFFER /* RTOS FreeRTOS Stream Buffers */
/* ARM::RTOS&FreeRTOS:Timers@11.1.0 */
#define RTE_RTOS_FreeRTOS_TIMERS        /* RTOS FreeRTOS Timers */
/* GigaDevice::Device:GD32F30x_StdPeripherals:ADC@1.0.2 */
#define RTE_DEVICE_STDPERIPHERALS_ADC
/* GigaDevice::Device:GD32F30x_StdPeripherals:EXTI@1.0.2 */
#define RTE_DEVICE_STDPERIPHERALS_EXTI
/* GigaDevice::Device:GD32F30x_StdPeripherals:GPIO@1.0.2 */
#define RTE_DEVICE_STDPERIPHERALS_GPIO
/* GigaDevice::Device:GD32F30x_StdPeripherals:I2C@1.0.2 */
#define RTE_DEVICE_STDPERIPHERALS_I2C
/* GigaDevice::Device:GD32F30x_StdPeripherals:MISC@1.0.2 */
#define RTE_DEVICE_STDPERIPHERALS_MISC
/* GigaDevice::Device:GD32F30x_StdPeripherals:PMU@1.0.2 */
#define RTE_DEVICE_STDPERIPHERALS_PMU
/* GigaDevice::Device:GD32F30x_StdPeripherals:RCU@1.0.2 */
#define RTE_DEVICE_STDPERIPHERALS_RCU
/* GigaDevice::Device:GD32F30x_StdPeripherals:TIMER@1.0.2 */
#define RTE_DEVICE_STDPERIPHERALS_TIMER
/* GigaDevice::Device:GD32F30x_StdPeripherals:USART@1.0.2 */
#define RTE_DEVICE_STDPERIPHERALS_USART


#endif /* RTE_COMPONENTS_H */
